---

- name: configure azure worker
  hosts: azure-workers
  vars_files:
    - vars.yml

  roles:
    - epel
    - docker
    - azure-docker-group
    - pip
    - build_tools
    - python-build-headers
    - azure-python
